apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki
  namespace: loki
spec:
  rules:
  - host: loki.eohcloud.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki-stack
            port:
              number: 3100

