---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
  namespace: loki
  labels:
    type: nfs
    app: loki
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.249.66.31
    path: "/loki"
