test_pod:
  image: bats/bats:v1.1.0
  pullPolicy: IfNotPresent

loki:
  enabled: true
  persistence:
    type: pvc      
    enabled: true
    storageClassName: managed-nfs
    accessModes:
    - ReadWriteMany
    size: 10Gi
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: {}
    uid: ""

promtail:
  enabled: false
  extraPorts:
    syslog:
      name: tcp-syslog
      containerPort: 1514
      service:
        port: 1514
        type: NodePort
  config:
    snippets:
      extraScrapeConfigs: |
        # Add an additional scrape config for syslog
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:1514
            labels:
              job: syslog
          relabel_configs:
            - source_labels:
                - __syslog_message_hostname
              target_label: hostname
            - source_labels: [__syslog_message_hostname] 
              target_label: host 
            - source_labels: [__syslog_message_hostname] 
              target_label: hostname 
            - source_labels: [__syslog_message_severity] 
              target_label: level 
            - source_labels: [__syslog_message_app_name] 
              target_label: application 
            - source_labels: [__syslog_message_facility] 
              target_label: facility 
           - source_labels: [__syslog_connection_hostname] 
             target_label: connection_hostname
            # example label values: kernel, CRON, kubelet
            - source_labels:
                - __syslog_message_app_name
              target_label: app
            # example label values: debug, notice, informational, warning, error
            - source_labels:
                - __syslog_message_severity
              target_label: level
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push

fluent-bit:
  enabled: false

grafana:
  enabled: false
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: 8.3.5

prometheus:
  enabled: false
  isDefault: false
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
  datasource:
    jsonData: {}

filebeat:
  enabled: false
  filebeatConfig:
    filebeat.yml: |
      # logging.level: debug
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      output.logstash:
        hosts: ["logstash-loki:5044"]

logstash:
  enabled: false
  image: grafana/logstash-output-loki
  imageTag: 1.0.1
  filters:
    main: |-
      filter {
        if [kubernetes] {
          mutate {
            add_field => {
              "container_name" => "%{[kubernetes][container][name]}"
              "namespace" => "%{[kubernetes][namespace]}"
              "pod" => "%{[kubernetes][pod][name]}"
            }
            replace => { "host" => "%{[kubernetes][node][name]}"}
          }
        }
        mutate {
          remove_field => ["tags"]
        }
      }
  outputs:
    main: |-
      output {
        loki {
          url => "http://loki:3100/loki/api/v1/push"
          #username => "test"
          #password => "test"
        }
        # stdout { codec => rubydebug }
      }

# proxy is currently only used by loki test pod
# Note: If http_proxy/https_proxy are set, then no_proxy should include the
# loki service name, so that tests are able to communicate with the loki
# service.
proxy:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

