apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-storage
  namespace: monitoring
  labels:
    type: nfs
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.249.66.31
    path: "/grafana"
